# Copyright 2014-2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

sudo: false
language: rust

env:
  - FLAGS=
  - FLAGS="--features glium"
script:
  - cargo build --verbose $(echo $FLAGS)
  - cargo test  --verbose $(echo $FLAGS)

# TODO: Check rustfmt, rust-analysis, clippy

cache:
  directories:
    - ~/.cargo
    - target
